# -*- coding: utf-8 -*-
"""
@author: Josh Kemppainen
Revision 1.0
February 27th, 2024
Michigan Technological University
1400 Townsend Dr.
Houghton, MI 49931

    ****************************************************************
    * Requirements:                                                *
    *   python 3.7+                                                *
    *                                                              *
    * Dependencies:                                                *
    *   python matplotlib module:                                  *
    *    - pip3 install matplotlib (if pip manager is installed)   *
    *                                                              *
    * Run methods:                                                 *
    *   - GUI (manipulate variables and run from. Default          *
    *          settings set from this script)                      *
    *                                                              *
    * Notes for Anaconda Spyder IDE users:                         *
    *   - If running this from the Anaconda Spyder IDE, before     *
    *     running you will have to turn on the interactive plot    *
    *     if you want the interactive plot to pop-up. You may do   *
    *     this by executing the following command in the console:  *
    *        %matplotlib qt                                        *
    *     Then to turn back on the inline plotting, where the plots*
    *     will appear in the Plots tab execute the following       *
    *     command in the console:                                  *
    *        %matplotlib inline                                    *
    ****************************************************************
"""
##################################################################################################################
# Python int value to range from 0 to 200 to control the GUI zoom. Where it option was added to account for the  #
# different ways individuals have their OS display settings setup. A GUI_zoom = 100, means that default settings #
# are used, whereas a GUI_zoom = 120 means increase GUI size by 20% and GUI_zoom = 80 means decrease GUI by 20%. #
# Examples:                                                                                                      #
#   GUI_zoom = 100 # use default GUI size                                                                        #
#   GUI_zoom = 75  # decrease GUI size by 25%                                                                    #
#                                                                                                                #
# Update use_GUI and GUI_zoom as desired.                                                                        #
##################################################################################################################
GUI_zoom = 100


##################################################################################################################
# blank_mode built by Josh Kemppainen 2/23/2024 to allow the GUI to load with very little predefined settings.   #
# This blank mode provides a basic template of the minimum number of settings that need to be supplied to the    #
# GUI during intialization.                                                                                      #
#                                                                                                                #
# Please refer to src/log_analysis/modes to see all predefined default modes. When users generate new modes a    #
# recommended naming convention is FML_code_purpose.py, wher F=first, M=middile, and L=last names. As all        #
# predefined modes are named default_code_purpose.py, allowing for easy sorting and book keeping for any modes   #
# generated by the user.                                                                                         #
##################################################################################################################
blank_mode = {'logfile': 'UPDATE-ME',       # Default logfile name to load during GUI initialization
              'keywords': ['Step', 'Temp'], # Keywords to find logged data (i.e. the columns of data)
              'sections': 'all',            # Sections from logfile to load (all or 1 or 1,2,3 or 1-3 or 1,2,4-6 or ...)
              'xdata': '',                  # Column name in log file for xdata to plot
              'ydata': '',                  # Column name in log file for ydata to plot
              'xlabel':'',                  # xlabel to set on plot (if empty the 'xdata' column name will be used)
              'ylabel':'',                  # ylabel to set on plot (if empty the 'ydata' column name will be used)
              'xscale'  : '',               # multipler value to scale 'xdata' by (float or fraction or empty)
              'yscale'  : '',               # multipler value to scale 'ydata' by (float or fraction or empty)
              'analysis': []}               # list of different analysis to load (if empty nothing will be loaded) 
                                            #   If providing a sublist for an auto-loaded the indexes are as follows:
                                            #     [<method>, <xlo>, <xhi>, <misc>, <name>], where:
                                            #
                                            #      - <method>  is a string and can be 'average' or 'cursor' or
                                            #                  'linear regression' or 'moving average' or 'skip'.
                                            #
                                            #      - <xlo>     is a float to set the lower boundary of the
                                            #                  region to apply the <analysis-type>. 
                                            #
                                            #      - <xhi>     is a float to set the upper boundary of the
                                            #                  region to apply the <analysis-type>. 
                                            #
                                            #       - <misc>   is a string to over ride certain default values,
                                            #                  such as the window of data points to use in the
                                            #                  'moving average'. For more details please run
                                            #                  code and click the "analysis help" button.
                                            #
                                            #       - <name>   is a string to set the name of the analysis in the
                                            #                  legend of the plot.
                                            #   Look at the other modes for examples on how to build a custom
                                            #   analysis mode or to adjust the analysis mode for your models.


##################################################################################################################
# Define basic settings, such as the 'mode' to load with, the predefined modes, and the figure image quality.    #
#                                                                                                                #
# Update settings as desired.                                                                                    #
##################################################################################################################
settings = {'mode': 'src/log_analysis/modes/default_blank.py', # Default run mode to load GUI with
            'modes-dir': 'src/log_analysis/modes',     # Set directory where all modes are saved
            'save-fig' : True,                         # True or False option to save figure are .jpeg
            'image-dpi': 300,                          # Set the image quality of the generated image (NOTE higher dpi's will result in slower code)
           }


###################################
### Import needed files and run ###
###################################
if __name__ == "__main__":  
    import src.log_analysis.GUI as GUI
    GUI.GUI(settings, GUI_zoom)