#!/bin/bash
#
# This is a custom batch script to usage with LUNAR/array_lmp_script.py for
# automatic array generation of LAMMPS scripts and batch scripts. Currently
# there are the following find strings set in this script that should have
# a match in the batch_array section:
#   $<ncores>
#   $<que>
#   $<account>
#   $<email>
#   $<input>
# In LUNAR/src/array_lmp_script/modes the template batch script for these
# find and replace strings is: HPC_carpenter_pbs_mpi_LAMMPS_29Aug2024.py
#
# This file was generated by Josh Kemppainen 9/17/2025 to run C3MD simulations
# on the ERDC Carpenter HPC. This script is basic, but has enough setup to run
# most of the simulations needed for C3MD. For guidance on PBS visit:
#   https://centers.hpc.mil/users/docs/erdc/carpenterPbsGuide.html
#
# To submit this script use: 
#    qsub Carpenter_mpi_slurm_mpi_slurm.sh
#
# To check  status of all running sims use:
#    qstat -u User_Name
#
# To kill a simulation use:
#    qdel job_id
#
# To check available resources run:
#    show_usage
#
#PBS -q $<que>
#PBS -l walltime=168:00:00
#PBS -A $<account>
#PBS -l select=1:ncpus=192:mpiprocs=$<ncores>
#PBS -M $<email>
#PBS -m abe
#PBS -o out.out
#PBS -e error.err
#
# Load and list modules
module purge
module load gcc/14.2.0
module load mpi/2021.13
module list

# Prepare to run the simulation
export LAMMPS="/p/home/${USER}/programs/lammps-29Aug2024"

# Input/Output files
JOB=$PBS_JOBID
NPROCS=$BC_MPI_TASKS_ALLOC
INPUT_FOLDER=$PBS_O_WORKDIR
INPUT_FILE="$<input>"
OUTPUT_FILE=${INPUT_FILE}.log.o${JOB}

# Run the simulation
cd ${INPUT_FOLDER}
mpiexec -n ${NPROCS} ${LAMMPS}/src/lmp_mpi -in ${INPUT_FILE} -log ${OUTPUT_FILE} | tee ${INPUT_FILE}.sh.o${JOB}

# List modules
module list