#!/bin/bash
#
# This is a custom batch script to usage with LUNAR/array_lmp_script.py for
# automatic array generation of LAMMPS scripts and batch scripts. Currently
# there are the following find strings set in this script that should have
# a match in the batch_array section:
#   $<ncores>
#   $<que>
#   $<account>
#   $<email>
#   $<input>
# In LUNAR/src/array_lmp_script/modes the template batch script for these
# find and replace strings is: HPC_carpenter_pbs_mpi_LAMMPS_29Aug2024.py
#
# This file was generated by Josh Kemppainen 9/17/2025 to run C3MD simulations
# on the Navy Nautilus HPC. This script is basic, but has enough setup to run
# most of the simulations needed for C3MD. For guidance on Slurm visit:
#   https://centers.hpc.mil/users/docs/navy/nautilusSlurmGuide.html#queueInfo
#
# To submit this script use: 
#    sbatch Nautilus_mpi_slurm.sh
#
# To check  status of all running sims use:
#    squeue -u user_name
#
# To kill a simulation use:
#    scancel job_id
#
# To check available resources run:
#    show_usage
#
#SBATCH --qos=$<que>
#SBATCH --account=$<account>
#SBATCH --export=ALL
#SBATCH --time=168:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=$<ncores>
#SBATCH --ntasks-per-node=128
#SBATCH --mail-user=$<email>
#SBATCH --mail-type=ALL
#SBATCH --output=out_%j.out
#SBATCH --error=error_%j.err
#
# Load and list modules
module purge
module load gcc/13.2.0
module load mpich/gnu/3.3.2
module load slurm
module list

# Prepare to run the simulation
export LAMMPS="/p/home/${USER}/programs/lammps-29Aug2024"

# Input/Output files
JOB=$SLURM_JOB_ID
INPUT_FOLDER="${PWD}"
INPUT_FILE="$<input>"
OUTPUT_FILE=${INPUT_FILE}.log.o${JOB}

# Run the simulation
srun ${LAMMPS}/src/lmp_mpi -in ${INPUT_FOLDER}/${INPUT_FILE} -log ${INPUT_FOLDER}/${OUTPUT_FILE} | tee ${INPUT_FILE}.sh.o${JOB}

# List modules
module list